files:
  - source: /BiglyBT/src/**/res/values/strings*.xml
    translation: /%original_path%-%two_letters_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        he: iw
        es-VE: es-rVE
  - source: /BiglyBT/src/**/res.lang/values/strings*.xml
    translation: /%original_path%-%two_letters_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        he: iw
        es-VE: es-rVE
